### ISSUE TITLE
Adapter should re-register back after any test is finished

### ISSUE THREAD

**Issue by MidhunSureshR** [matrix-org/trafficlight-adapter-element-web#13]

**Comment by michaelkaye** [comment]
My plan for this is that the adapter becomes a single-shot; that way we always run it in an external loop (eg `while sleep 1; do yarn test:trafficlight; done;`) or via another management system (systemd service, k8s statefulset). That way we avoid the memory leaks that seem to creep in after we run cypress from the same process too many times.  (i've seen this after ~10 runs)

**Comment by michaelkaye** [comment]
Adapter is being used single-shot, and doing this clears out the state neatly and resets us for the next cycle.
