### ISSUE TITLE
See if there is a better alternative than using a wait action in the client

### ISSUE THREAD

**Issue by MidhunSureshR** [matrix-org/trafficlight-adapter-element-web#5]
See https://github.com/matrix-org/trafficlight-adapter-element-web/pull/2#issuecomment-1262563890

**Comment by michaelkaye** [comment]
With the update to trafficlight test setup, we can now do:

```
await asyncio.sleep(500)
```
in the server side of the tests, to allow time to pass without requiring an explicit wait from the clients.

I believe i have removed all the use of the `wait` command from the server side, so we can probably remove this client-side now.

**Comment by michaelkaye** [comment]
eg https://github.com/matrix-org/trafficlight/blob/07770ae5ab9d42c79a025d434fc78473593a69b2/trafficlight/tests/retry_sendToDevice_test.py#L42
